POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@yopmail.com",
  "password": "securepassword",
  "role": "support agent"
}

###Login to JWT Token66ba28593e9ea8d59910445a

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "securepassword"
}

###Create Ticket
POST http://localhost:3000/tickets/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmJhNWUyYjk4MWEzYWY3YTg5MTlkODgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjM1MjE0NTgsImV4cCI6MTcyMzUyNTA1OH0.tLB6Id7PeSWU9ZDPN0Tmm8ZRs1fkJNENwj0JLoSZAgE
Content-Type: application/json

{
  "title": "Issue with the Customer Support new"
}

###Update Ticket

PATCH http://localhost:3000/tickets/update/66ba56e1ed18230b62318dc1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmJhNTY5YmVkMTgyMzBiNjIzMThkYmIiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3MjM0ODc5MzYsImV4cCI6MTcyMzQ5MTUzNn0.2RdUWJCVcw19lNOT8irV3t2ETpTZqXPTttpZMI4TrHo
Content-Type: application/json

{
  "status": "InProgress",
  "title": "Issue with the product (Updated) by Agent"
}

###Delete Ticket

DELETE http://localhost:3000/tickets/delete/66ba5607ed18230b62318db3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmJhNTQwOWIyZTAyNjU2NTczNjZhYTEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjM0ODc3MzUsImV4cCI6MTcyMzQ5MTMzNX0.TAxZHI5VI8C5-YyuwwGERx4mauK36sIqx4HvlwsxmSg
Content-Type: application/json


###Assign Ticket

PATCH http://localhost:3000/tickets/assign/66bad9d38c1fba260bf8a1c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmJhZGE0NzhjMWZiYTI2MGJmOGExYzgiLCJyb2xlIjoic3VwcG9ydCBhZ2VudCIsImlhdCI6MTcyMzUyMTYyNywiZXhwIjoxNzIzNTI1MjI3fQ.Mji3rp8PCQDr4LwgWPGoM3w14zreu40sghR3rYHKovs
Content-Type: application/json

{
  "assignedTo": "support"
}


###